name: Docs Deploy
on:
  release:
    types:
      - published
permissions:
  contents: write
jobs:
  deploy:
    name: Deploy Docs to GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with docs
      - name: GH Pages deploy
        run: |
          cd docs
          git pull
          poetry run hatch version
          poetry run mike deploy --push --update-aliases `poetry run hatch version` stable