name: Pypi Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Pypi Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Extract Release Name
        run: echo "RELEASE_NAME=$(echo $GITHUB_REF | sed -n 's/refs\/tags\///p')" >> $GITHUB_ENV
      - name: Install hatch
        run: pip install hatch
      - name: Publish to Pypi
        run: |
          hatch version $RELEASE_NAME
          hatch build
          hatch publish -r test -n
      - name: Commit new version
        run: |
          git checkout main
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update version number to $RELEASE_NAME."
          git push
