name: Pypi Publish

on:
  release:
    types:
      - published
env:
  HATCH_INDEX_AUTH: ${{ secrets.HATCH_INDEX_AUTH }}
  HATCH_INDEX_USER: ${{ secrets.HATCH_INDEX_USER }}

jobs:
  publish:
    name: Pypi Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install hatch
        run: pip install hatch
      - name: Publish to Pypi
        run: |
          hatch build
          hatch publish -n
